wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=toor
     - WORDPRESS_DB_USER=root
    ports:
     - "192.168.100.8:80:80"
    volumes:
     - ./html:/var/www/html
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=toor
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
